# .github/workflows/build-and-deploy.yml

name: Static site build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch export/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          branch: gh-pages
          folder: export
