name: Static site build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
          touch dist/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          branch: gh-pages
          folder: dist
