name: Fetch data

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Get data
        run: python src/beachland.py > beachland.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Updating file
          branch: ${{ github.head_ref }}
