name: Fetch data

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Get data
        run: |
          python script/beachland.py > src/data/beachland.json
          python script/grogshop.py > src/data/grogshop.json
          python script/mahalls.py > src/data/mahalls.json
          python script/agora.py > src/data/agora.json
          python script/hob.py > src/data/hob.json
      - name: Merge data
        run: python script/merge.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 press Ⓧ to json
          branch: ${{ github.head_ref }}
